# /prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']  # Scrape the frontend metrics

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:5000']  # Scrape the backend metrics
